Added visionOS build & unit test to GitHub CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -222,3 +222,48 @@ jobs:
     - name: Unit Tests
       if: steps.destnameprep.outcome != 'failure'
       run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=watchOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+
+  visionOS:
+    name: visionOS
+    runs-on: macos-15-arm64 # visionOS Simulator requires Apple Silicon
+    timeout-minutes: 20
+    steps:
+    - uses: actions/checkout@main
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable
+    - name: Bootstrap Platforms
+      # Workaround for Xcode/GitHub runner issues finding simulators.
+      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
+      run: xcrun simctl list
+    - name: Download Platform
+      # Workaround for Xcode/GitHub runner issues finding simulators.
+      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
+      run: xcodebuild -downloadPlatform visionOS
+    - name: Build
+      run: xcodebuild build -skipMacroValidation -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=visionOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: Prepare Destination Device Name
+      id: destnameprep
+      # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
+      # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
+      # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
+      # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
+      # be no way to "cancel" an individual job programmatically.
+      continue-on-error: true
+      shell: bash
+      run: |
+        xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
+        SIMPLATFORM="visionOS"
+        SIMDEVICE="Apple\sVision\sPro"
+        REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
+        SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
+        if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
+        echo "Available $SIMPLATFORM simulators:"
+        echo "$SIMPATFORMLIST"
+        DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
+        if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
+        echo "Using device name \"$DESTNAME\""
+        echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
+    - name: Unit Tests
+      if: steps.destnameprep.outcome != 'failure'
+      run: xcodebuild test -skipMacroValidation -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=visionOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
